### ISSUE TITLE
Make build dependencies optional

### ISSUE THREAD

**Issue by neachdainn** [jeikabu/nng-rust#12]
Both of the current build dependencies can be put behind feature flags. Additionally, unless Bindgen is behind a feature flag there is still a chance that `libclang` will be required at build time.

**Comment by jeikabu** [comment]
I want to say I tried to do that, but I think there was a problem with making dev-dependencies "optional".  I may not be remembering correctly, though...

If it can't be done, I did already remove clang from my docker images for armv7 and aarch64, and literally just today I can a quick test on a pretty low-end armv6 device with almost nothing on it.  My point is even I'll notice if the dependency slips in.

Could also re-enable the win32 build on appveyor since their environment doesn't provide 32-bit llvm.

**Comment by neachdainn** [comment]
You can't make dev-dependencies optional but you can make build-dependencies optional. If there ends up being problems with making them optional, I'm find with monitoring to make sure it doesn't show up. That being said, I do have a preference for setting things up so we don't have to monitor.
