### ISSUE TITLE
Not following SemVer

### ISSUE THREAD

**Issue by neachdainn** [jeikabu/nng-rust#30]
There are breaking changes from `v1.1*` to `v1.2*` and from `v1.2*` to `v1.3*`. Probably not a whole lot we can do about that but it's worth keeping a better eye out for it in the future.

**Comment by jeikabu** [comment]
Yeah, being low-level bindings I still feel it's more important to provide a clear mapping to nng rather than a slavish adherence to semver. Especially since we may not even be aware of breaking changes within nng itself. 

The top of the readme clearly specifies the versioning scheme. Being "rc" release candidates they're all tagged as pre-release/unstable. When I last raised this use-case to the cargo/crates.io teams there was no better solution given the current interpretation of semver. Baring toolchain/support improvements or extensions to semver it's impossible to have it both ways.

It's better dealt with in upstream crates.

**Comment by neachdainn** [comment]
I believe the breaking changes I am talking about was a product of how we are generating the bindings, not due to any change in nng. In the transition from `v1.2.4-rc.1` many of the `size_t` parameters (`u64`) were changed into `usize` without any corresponding change in nng.

**Comment by jeikabu** [comment]
Ah yes, that came from bindgen.  I was a bit skeptical about that, but assumed it was done for "correctness".
Turns out there's a new flag [that doesn't work](https://github.com/rust-lang/rust-bindgen/issues/1770).
