### ISSUE TITLE
Socket address family enum should either be C-style or have TryFrom

### ISSUE THREAD

**Issue by neachdainn** [jeikabu/nng-rust#8]
Doing a match on the `nng_sockaddr_family` type is currently a bit painful. It either needs to be a C-style enum or have a function to easily convert to/from an integer.

**Comment by neachdainn** [comment]
In general, I'm not sure I see the value of having these enums be anything other than C-style if the functions do not take them as enums. Using the Pipe events as an example, I have to make a conversion from `i32 -> nng_pipe_ev` during the callback and I have to convert from `nng_pipe_ev -> i32` when I call the `nng_pipe_notify` function. No safety is gained by type checking but it does make the code look worse.

**Comment by jeikabu** [comment]
Personally, I really like Rust's strong-typing and static analysis.  Naked integers everywhere are error-prone and generally un-safe.  `nng_pipe_notify()` is effectively lying; its prototype claims a parameter may be any valid `int` but in practice it can only be a value from `nng_pipe_ev` (and excluding `NNG_PIPE_EV_NUM`).
Sticking with `int` makes it easy to write nonsense like:
```rust
extern "C" fn notify_callback(_pipe: nng_pipe, event: i32, _arg: PipeNotifyCallbackArg) {
    match event {
        value if value == NNG_PIPE_EV_ADD_PRE as i32 => {}, // might be possible to get `const u32` instead
        NNG_DURATION_INFINITE => {},
        0x0fff_1234 => {},
        _ => panic!(),
    };
```
Because it's an `int` you __have__ to use `_` in order to get an "exhaustive" match.

Contrast that with:
```rust
extern "C" fn notify_callback(_pipe: nng_pipe, event: i32, _arg: PipeNotifyCallbackArg) {
    match nng_pipe_ev::try_from(event) {
        Ok(NNG_PIPE_EV_ADD_PRE) => {},
        Ok(NNG_PIPE_EV_ADD_POST) => {},
        Ok(NNG_PIPE_EV_REM_POST) => {},
        _ => panic!(),
    };
// OR
match nng_pipe_ev::try_from(event).unwrap() {
        NNG_PIPE_EV_ADD_PRE => {},
        NNG_PIPE_EV_ADD_POST => {},
        NNG_PIPE_EV_REM_POST => {},
        NNG_PIPE_EV_NUM => panic!(),
    };
}
```

Let's add another event type `NNG_PIPE_EV_REM_PRE` in `nng.h`:
```c
typedef enum {
	NNG_PIPE_EV_ADD_PRE,  // Called just before pipe added to socket
	NNG_PIPE_EV_ADD_POST, // Called just after pipe added to socket
	NNG_PIPE_EV_REM_PRE,
	NNG_PIPE_EV_REM_POST, // Called just after pipe removed from socket
	NNG_PIPE_EV_NUM,      // Used internally, must be last.
} nng_pipe_ev;
```
Compile time error:
```
error[E0004]: non-exhaustive patterns: `NNG_PIPE_EV_REM_PRE` not covered
  --> runng/tests/tests/pipe_tests.rs:14:11
   |
14 |     match nng_pipe_ev::try_from(event).unwrap() {
   |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ pattern `NNG_PIPE_EV_REM_PRE` not covered
```

The `int` version can only catch this at runtime via `_ => panic!()`.

If you'd rather have `int` we can do that; I can maintain an `enum` in my code.  But if I wanted type ambiguity everywhere I would just use C.

**Comment by jeikabu** [comment]
When you have weak types it tends to pollute all the code it touches:
```rust
// Where `pub type nng_pipe_ev = u32;`
fn notify_helper(_: nng_pipe_ev) {}

#[test]
fn bad_type() {
    // Compiles, but wrong...
    notify_helper(NNG_FLAG_ALLOC);
    notify_helper(1024);
}
```
I guess my point is that we can't do anything about the Rust FFI boundaries being unsafe, but we should force the native values to go through explicit conversions so we can benefit from Rust's safety guarantees as soon as possible.

**Comment by neachdainn** [comment]
> If you'd rather have `int` we can do that; I can maintain an `enum` in my code. But if I wanted type ambiguity everywhere I would just use C.

It sounds like you have a stronger opinion on this than I do, so I am fine keeping it strongly typed. Plus, your NNG pull request (mentioned in #9) also helps with this.
